name: Scrape & Analyze Decor (cron)

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)
  workflow_dispatch: {}       # manual run button

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Scrape Reddit
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python scripts/scrape_reddit.py \
            --subs HomeDecorating InteriorDesign CozyPlaces \
            --days 7 \
            --limit 2000 \
            -o data/decor_reddit_raw.csv

      - name: Analyze & Export CSVs
        run: python scripts/analyze_decor.py

      - name: Commit & push data
        run: |
          git config user.name "pld-bot"
          git config user.email "pld-bot@users.noreply.github.com"
          git add data/*.csv || true
          git commit -m "chore: refresh decor data" || echo "No changes"
          git push
