name: Scrape & Analyze (NO-REDDIT, unsupervised)

on:
  schedule:
    - cron: "0 * * * *"   # hourly (UTC). Change to */30 for every 30 minutes, */15 for 15.
  workflow_dispatch: {}

concurrency:
  group: prettydata-no-reddit
  cancel-in-progress: true

jobs:
  topics:
    name: Build topic (${{ matrix.topic }})
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        topic: [decor, fashion, design, beauty]
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data folder
        run: mkdir -p data

      # --- Ingest (non-Reddit) sources --------------------------------------
      - name: RSS (${{ matrix.topic }} · 45d)
        continue-on-error: true
        run: |
          python scripts/ingest_rss.py \
            --feeds data/feeds_${{ matrix.topic }}.txt \
            --days 45 \
            -o data/${{ matrix.topic }}_rss_raw.csv

      - name: Google News (${{ matrix.topic }} · 45d)
        continue-on-error: true
        run: |
          python scripts/ingest_gnews.py \
            --queries data/news_queries_${{ matrix.topic }}.txt \
            --days 45 \
            -o data/${{ matrix.topic }}_gnews_raw.csv

      - name: YouTube (${{ matrix.topic }} · 45d)
        continue-on-error: true
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          python scripts/ingest_youtube.py \
            --queries data/youtube_queries_${{ matrix.topic }}.txt \
            --days 45 --max_per_query 25 \
            -o data/${{ matrix.topic }}_youtube_raw.csv

      - name: Combine sources (${{ matrix.topic }})
        run: |
          python scripts/combine_sources.py \
            --inputs data/${{ matrix.topic }}_rss_raw.csv data/${{ matrix.topic }}_gnews_raw.csv data/${{ matrix.topic }}_youtube_raw.csv \
            -o data/${{ matrix.topic }}_all_raw.csv

      # --- New: per-topic analyzer (clean phrases + smart ranking) -----------
      - name: Analyze topic (${{ matrix.topic }})
        run: |
          python scripts/analyze_topic.py \
            --topic ${{ matrix.topic }} \
            --raw data/${{ matrix.topic }}_all_raw.csv \
            -o data/${{ matrix.topic }}

      - name: Commit per-topic artifacts
        run: |
          git config user.name "pld-bot"
          git config user.email "pld-bot@users.noreply.github.com"
          git add data/${{ matrix.topic }}_* || true
          git commit -m "no-reddit: refresh ${{ matrix.topic }} (rss+gnews+youtube+topic-analysis)" || echo "No changes"
          for i in 1 2 3; do
            git pull --rebase || true
            git push && break || sleep 2
          done

  unsupervised:
    name: Unsupervised (ALL web)
    needs: topics
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Combine ALL topics
        run: |
          python scripts/combine_sources.py \
            --inputs data/decor_all_raw.csv data/fashion_all_raw.csv data/design_all_raw.csv data/beauty_all_raw.csv \
            -o data/all_all_raw.csv

      - name: Analyze unsupervised (ALL web)
        run: |
          python scripts/analyze_unsupervised.py \
            --raw data/all_all_raw.csv \
            --min_df 4 --max_df 0.6 --new_weeks 6 \
            -o data/all

      - name: Commit unsupervised artifacts
        run: |
          git config user.name "pld-bot"
          git config user.email "pld-bot@users.noreply.github.com"
          git add data/all_* || true
          git commit -m "no-reddit: unsupervised trend discovery (ALL web)" || echo "No changes"
          for i in 1 2 3; do
            git pull --rebase || true
            git push && break || sleep 2
          done
