name: Scrape & Analyze (PrettyData — multi)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

concurrency:
  group: prettydata-scrape
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure data folder
        run: mkdir -p data

      # ---------- DECOR ----------
      - name: Scrape Reddit (decor · last 90 days)
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python scripts/scrape_reddit.py \
            --subs HomeDecorating InteriorDesign CozyPlaces \
            --days 90 \
            --limit 4000 \
            -o data/decor_reddit_raw.csv

      - name: Analyze (decor)
        run: |
          python scripts/analyze_prettydata.py \
            --raw data/decor_reddit_raw.csv \
            --terms-file data/terms_decor.json \
            --prefix decor

      # ---------- FASHION ----------
      - name: Scrape Reddit (fashion · last 90 days)
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python scripts/scrape_reddit.py \
            --subs malefashionadvice femalefashionadvice streetwear frugalmalefashion \
            --days 90 \
            --limit 4000 \
            -o data/fashion_reddit_raw.csv

      - name: Analyze (fashion)
        run: |
          python scripts/analyze_prettydata.py \
            --raw data/fashion_reddit_raw.csv \
            --terms-file data/terms_fashion.json \
            --prefix fashion

      # ---------- DESIGN (graphic/industrial/web) ----------
      - name: Scrape Reddit (design · last 90 days)
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python scripts/scrape_reddit.py \
            --subs graphic_design design typography web_design industrialdesign \
            --days 90 \
            --limit 4000 \
            -o data/design_reddit_raw.csv

      - name: Analyze (design)
        run: |
          python scripts/analyze_prettydata.py \
            --raw data/design_reddit_raw.csv \
            --terms-file data/terms_design.json \
            --prefix design

      # ---------- AESTHETICS (combine decor + fashion) ----------
      - name: Combine raw for aesthetics
        run: |
          python - <<'PY'
          import pandas as pd, os
          paths = ["data/decor_reddit_raw.csv","data/fashion_reddit_raw.csv"]
          frames = [pd.read_csv(p) for p in paths if os.path.exists(p)]
          (pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()).to_csv("data/aesthetics_reddit_raw.csv", index=False)
          PY

      - name: Analyze (aesthetics)
        run: |
          python scripts/analyze_prettydata.py \
            --raw data/aesthetics_reddit_raw.csv \
            --terms-file data/terms_aesthetics.json \
            --prefix aesthetics

      # ---------- commit ----------
      - name: Commit & push data artifacts
        run: |
          git config user.name "pld-bot"
          git config user.email "pld-bot@users.noreply.github.com"
          git add data/*.csv || true
          git commit -m "chore: refresh prettydata (decor+fashion+design+aesthetics)" || echo "No changes"
          git pull --rebase || true
          git push || true
